env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  func-names: "off"
  react/jsx-uses-react: "off"
  react/react-in-jsx-scope: "off"
  react/display-name: "off"
  "@typescript-eslint/no-explicit-any": "off"
  "@typescript-eslint/no-unused-vars": "warn"
